Source/Controllers/ChartController.cs
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using QLCLDA.Models;
using QLCLDA.Models.Chart;
using QLCLDA.Models.Entity;

namespace QLCLDA.Controllers
{
    public class ChartController : Controller
    {
        private readonly qlcldaEntities _db = new qlcldaEntities();

        // GET: /Chart/
        public ActionResult Index()
        {
            return View();
        }

        //Biểu đồ số lượng dự án của từng nhóm
        public ActionResult TeamProjectCount()
        {
            var chartDraw = new ChartDraw();

            var q = from t in _db.teams
                    select new { t.name, value = t.projects.Count() };

            //chartDraw.ProjectCount = new List<ChartValue>();
            foreach (var item in q)
            {
                chartDraw.ProjectCount.Add(new ChartValue
                {
                    name = item.name,
                    value = item.value
                });
            }

            return View(chartDraw);
        }

        //Biểu đồ số lượng dự án theo quy mô
        public ActionResult ScaleProjects()
        {
            var chartDraw = new ChartDraw();

            var q = (from p in _db.projects
                     select new { QM = p.scale_estimator }).ToList();

            var q1 = q.Count(s => s.QM <= 3);
            var q2 = q.Count(s => s.QM > 3 && s.QM <= 10);
            var q3 = q.Count(s => s.QM > 10 && s.QM <= 50);
            var q4 = q.Count(s => s.QM > 50);

            chartDraw.RevenueTeam = new List<ChartValue>
            {
                new ChartValue { name = "< 3 man/month", value = q1 },
                new ChartValue { name = "3 - 10 man/month", value = q2 },
                new ChartValue { name = "10 - 50 man/month", value = q3 },
                new ChartValue { name = "> 50 man/month", value = q4 }
            };

            return View(chartDraw);
        }

        //Biểu đồ phần trăm doanh thu giữa các team
        public ActionResult RevenueTeams()
        {
            var chartDraw = new ChartDraw();

            //Phần trăm doanh thu giữa các team
            var q = from t in _db.teams
                    select new
                    {
                        t.name,
                        value = t.projects.Where(p => p.end_project != null).Sum(p => p.contract_value)
                    };

            //chartDraw.RevenueTeam = new List<ChartValue>();
            foreach (var item in q)
            {
                chartDraw.RevenueTeam.Add(new ChartValue
                {
                    name = item.name,
                    value = item.value.GetValueOrDefault()
                });
            }

            //Phần trăm lợi nhuận giữa các team
            var q1 = from t in _db.teams
                     select new
                     {
                         t.name,
                         value = t.projects.Where(p => p.end_project != null).Sum(p => p.contract_value - p.current_cost)
                     };

            //chartDraw.ProfitTeams = new List<ChartValue>();
            foreach (var item in q1)
            {
                chartDraw.ProfitTeams.Add(new ChartValue
                {
                    name = item.name,
                    value = item.value.GetValueOrDefault()
                });
            }

            //Hiệu suất doanh thu/người từng team
            var q2 = from t in _db.teams
                     select new
                     {
                         t.name,
                         value = t.projects.Where(p => p.end_project != null).Sum(p => p.contract_value) / t.team_staff.Count()
                     };

            //chartDraw.RevenuePersonalTeam = new List<ChartValue>();
            foreach (var item in q2)
            {
                chartDraw.RevenuePersonalTeam.Add(new ChartValue
                {
                    name = item.name,
                    value = item.value.GetValueOrDefault()
                });
            }

            return View(chartDraw);
        }

        public ActionResult IsFailedTeam()
        {
            var chartDraw = new List<ChartDraw>();

            //Biểu đồ thành công/thất bại toàn công ty
            var q1 = from p in _db.end_project
                     where p.is_fail == true
                     select p;

            var q2 = from p in _db.end_project
                     select p;

            chartDraw.Add(new ChartDraw
            {
                name = "Toàn công ty",
                FailedEachTeam = new List<ChartValue>
                {
                        new ChartValue { name = "Thành công", value = q2.Count() - q1.Count() },
                        new ChartValue { name = "Thất bại", value = q1.Count() }
                    }
            });

            //Biểu đồ tỷ lệ thành công/thất bại của từng nhóm
            var q = (from t in _db.teams
                     where t.projects.Count() != 0 && (t.projects.Count(s => s.end_project.is_fail == true) != 0
                           || t.projects.Count(s => s.end_project.is_fail == false) != 0)
                     select new
                     {
                         t.name,
                         failed = t.projects.Count(s => s.end_project.is_fail == true),
                         sucess = t.projects.Count(s => s.end_project.is_fail == false)
                     }).ToList();

            chartDraw.AddRange(q.Select(item => new ChartDraw
            {
                name = item.name,
                FailedEachTeam = new List<ChartValue>
                {
                    new ChartValue {name = "Thành công", value = item.sucess},
                    new ChartValue {name = "Thất bại", value = item.failed}
                }
            }));

            return View(chartDraw);
        }

        //Biểu đồ số lượng dự án, doanh thu dự án theo năm
        public ActionResult RevenueYears()
        {
            var chartDraw = new ChartDraw();

            //Số lượng dự án theo năm
            var q = from p in _db.projects
                    group p by p.expected_start_date.Year into g
                    orderby g.Key
                    select g;

            foreach (var item in q)
            {
                chartDraw.NumberYear.Add(new ChartValue
                {
                    name = item.Key.ToString(CultureInfo.InvariantCulture),
                    value = item.Count()
                });
            }

            //Doanh thu dự án theo năm
            var q1 = from p in _db.projects
                     where p.end_project != null
                     group p by p.expected_start_date.Year into g
                     orderby g.Key
                     select g;

            foreach (var item in q1)
            {
                chartDraw.RevenueYear.Add(new ChartValue
                {
                    name = item.Key.ToString(CultureInfo.InvariantCulture),
                    value = item.Sum(p => p.contract_value).GetValueOrDefault()
                });
            }

            return View(chartDraw);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Source/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QLCLDA.Models;
using QLCLDA.Models.Entity;

namespace QLCLDA.Controllers
{
    public class TeamController : Controller
    {
        private readonly qlcldaEntities _db = new qlcldaEntities();

        // GET: /Team/
        public ActionResult Index()
        {
            var q = _db.teams.OrderBy(x => x.display_order).Include(s => s.team_staff).ToList();
            foreach (var team in q)
            {
                GetStaffInTeam(team);
            }

            return View(_db.teams.OrderBy(x => x.display_order).ToList());
        }

        // GET: /Team/Details/5
        public ActionResult Details(int? id, string startdate, string enddate)
        {
            startdate = string.IsNullOrEmpty(startdate) ? "01/01/2000" : startdate;
            enddate = string.IsNullOrEmpty(enddate) ? "01/01/2222" : enddate;
            IFormatProvider culture = new System.Globalization.CultureInfo("fr-FR", true);
            var sd = DateTime.Parse(startdate, culture, System.Globalization.DateTimeStyles.AssumeLocal);
            var ed = DateTime.Parse(enddate, culture, System.Globalization.DateTimeStyles.AssumeLocal);
            var d = from w in _db.works
                    where w.work_day >= sd && w.work_day <= ed
                    group w by w.work_day into g
                    select g.Key;
            ViewBag.day = d.OrderBy(x => x.Value).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var team = _db.teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
           /* var day = from ts in team.team_staff
                      from r in ts.staff.resources
                      from w in r.works
                      group w by w.work_day into g
                      select g.Key;
            ViewBag.day = day.OrderBy(x => x.Value).ToList();*/



            return View(team);
        }

        // GET: /Team/Create
        public ActionResult Create()
        {
            var team = new team { team_staff = new List<team_staff>() };
            PopulateAssignedStaffData(team);
            return View();
        }

        // POST: /Team/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,workplace,technique,display_order")] team team, string[] to_select_list, string[] leader_select_list)
        {
            if (to_select_list != null || leader_select_list != null)
            {
                team.team_staff = new List<team_staff>();

                if (to_select_list != null)
                {
                    foreach (var staff in to_select_list)
                    {
                        var staffToAdd = new team_staff { id_staff = int.Parse(staff), leader = false, is_main_team = true };
                        team.team_staff.Add(staffToAdd);
                    }
                }

                if (leader_select_list != null)
                {
                    foreach (var staff in leader_select_list)
                    {
                        var leaderToAdd = new team_staff { id_staff = int.Parse(staff), leader = true, is_main_team = true };
                        team.team_staff.Add(leaderToAdd);
                    }
                }
            }

            if (ModelState.IsValid)
            {
                _db.teams.Add(team);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(team);
        }

        // GET: /Team/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //team team = db.teams.Find(id);

            team team = _db.teams.Include(i => i.team_staff).Single(i => i.id == id);
            PopulateAssignedStaffData(team);

            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: /Team/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] to_select_list, string[] leader_select_list)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var teamToUpdate = _db.teams.Include(i => i.team_staff).Single(i => i.id == id);

            if (TryUpdateModel(teamToUpdate, ""))
            {
                try
                {
                    UpdateTeamStaffs(to_select_list, leader_select_list, teamToUpdate);

                    _db.Entry(teamToUpdate).State = EntityState.Modified;
                    _db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateAssignedStaffData(teamToUpdate);
            return View(teamToUpdate);
        }

        // GET: /Team/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            team team = _db.teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: /Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            team team = _db.teams.Find(id);

            var q = _db.team_staff;
            foreach (var staff in q.Where(staff => staff.id_team == team.id))
            {
                _db.team_staff.Remove(staff);
            }

            var allProjects = new HashSet<int>(team.projects.Select(p => p.id));
            foreach (var project in _db.projects)
            {
                if (allProjects.Contains(project.id))
                {
                    team.projects.Remove(project);
                }
            }

            _db.teams.Remove(team);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Lấy danh sách nhân sự đã có trong team
        private void GetStaffInTeam(team team)
        {
            var allStaffs = _db.staffs;
            var teamStaffs = new HashSet<int>(team.team_staff.Where(c => c.leader == false).Select(c => c.id_staff));
            var teamLeaders = new HashSet<int>(team.team_staff.Where(c => c.leader == true).Select(c => c.id_staff));

            var viewModel = new List<AssignedStaffData>();
            var viewLeader = new List<AssignedLeaderData>();

            foreach (var staff in allStaffs)
            {
                if (teamStaffs.Contains(staff.id))
                {
                    viewModel.Add(new AssignedStaffData
                    {
                        StaffId = staff.id,
                        Name = staff.name
                    });
                }

                if (teamLeaders.Contains(staff.id))
                {
                    viewLeader.Add(new AssignedLeaderData
                    {
                        LeaderId = staff.id,
                        Name = staff.name
                    });
                }
            }
            team.getStaffs = viewModel;
            team.getLeaders = viewLeader;
        }

        // Lấy danh sách nhân sự (Thông qua View Model A.S.D)
        private void PopulateAssignedStaffData(team team)
        {
            var allStaffs = _db.staffs;

            var staffsInTeam = new HashSet<int>(team.team_staff.Select(c => c.id_staff));
            var teamStaffs = new HashSet<int>(team.team_staff.Where(c => c.leader != true).Select(c => c.id_staff));
            var leaderTeams = new HashSet<int>(team.team_staff.Where(l => l.leader == true).Select(l => l.id_staff));

            var viewModel = new List<AssignedStaffData>();
            var viewLeader = new List<AssignedLeaderData>();
            var viewSit = new List<AssignedSit>();

            foreach (var staff in allStaffs)
            {
                viewSit.Add(new AssignedSit
                {
                    StaffId = staff.id,
                    Name = staff.name,
                    Assigned = staffsInTeam.Contains(staff.id)
                });

                viewModel.Add(new AssignedStaffData
                {
                    StaffId = staff.id,
                    Name = staff.name,
                    Assigned = teamStaffs.Contains(staff.id)
                });

                viewLeader.Add(new AssignedLeaderData
                {
                    LeaderId = staff.id,
                    Name = staff.name,
                    Assigned = leaderTeams.Contains(staff.id)
                });
            }

            ViewBag.Staffs = viewModel;
            ViewBag.Leaders = viewLeader;
            ViewBag.SIT = _db.staffs.Where(s => s.team_staff.Any() != true).ToList();
        }

        // Update dữ liệu trong bảng team_staff
        private void UpdateTeamStaffs(IEnumerable<string> selectedStaffs, string[] selectedLeader, team teamToUpdate)
        {

Source/Views/Shared/LayoutBill.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Thông tin chất lượng dự án</title>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
    @Styles.Render("~/Content/bootstrap3-editable/css/bootstrap-editable.css")
    @Styles.Render("~/Content/bill.css")


    @Styles.Render("~/Content/bootstrap3-editable/css/bootstrap-editable.css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <link rel="stylesheet" type="text/css" href="~/Content/dataTables/dataTables.bootstrap.css">
    <script type="text/javascript" language="javascript" src="~/Scripts/dataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="~/Scripts/dataTables/dataTables.bootstrap.js"></script>
    
    <script src="~/Content/bootstrap3-editable/js/jquery-2.0.3.min.js"></script>
    <script src="~/Content/bootstrap3-editable/js/bootstrap.min.js"></script>
    @Scripts.Render("~/Content/bootstrap3-editable/js/bootstrap-editable.min.js")
    @Scripts.Render("~/Content/main.js")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("QLCLDA", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>

                    <li class="dropdown">
                        @Html.ActionLink("Dự án", "Index", "Project")
                        <ul class=dropdown-menu>
                            <li>@Html.ActionLink("Loại dự án", "Index", "TypeProject")</li>
                            <li>@Html.ActionLink("Kết thúc dự án", "Index", "EndProject")</li>
                            <li>@Html.ActionLink("Đánh giá chất lượng", "Index", "Quality")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        @Html.ActionLink("Nhóm", "Index", "Team")
                        <ul class=dropdown-menu>
                            <li>@Html.ActionLink("Nhân sự", "Index", "Staff")</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("Khách hàng", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Báo cáo", "Index", "Chart")</li>
                </ul>

                @* Đăng nhập + Đăng xuất *@
                <ul style="float:right" class="nav navbar-nav">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Đăng nhập", "Login", "Account")</li>
                    }
                    else
                    {
                        @*<li><a href="#">Hi! @User.Identity.Name</a></li>*@
                        <li>@Html.ActionLink("Hi! " + User.Identity.Name, "ChangePassword", "Account")</li>
                        <li>@Html.ActionLink("Đăng xuất", "Logout", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Thông tin chất lượng dự án</p>
        </footer>
    </div>
</body>
</html>

Source/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Thông tin chất lượng dự án</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datepicker")
    @Scripts.Render("~/bundles/resource")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" type="text/css" href="~/Content/dataTables/dataTables.bootstrap.css">
    <script type="text/javascript" language="javascript" src="~/Scripts/dataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="~/Scripts/dataTables/dataTables.bootstrap.js"></script>

    @* Date picker *@
    <script type="text/javascript">
        $(function () {
            $(".datepicker").datepicker({
                changeMonth: true,
                changeYear: true
            });
        });
    </script>

    @* Checkbox list *@
    <script type="text/javascript">
        function toggle(source) {
            checkboxes = document.getElementsByName('foo');
            for (var i = 0, n = checkboxes.length; i < n; i++) {
                checkboxes[i].checked = source.checked;
            }
        }
    </script>

    @* dataTables *@
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $('#project').dataTable({
                "order": [[1, "asc"]]
            });
            $('#example').dataTable({
                "order": [[0, "asc"]]
            });
        });
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("QLCLDA", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>

                    <li class="dropdown">
                        @Html.ActionLink("Dự án", "Index", "Project")
                        <ul class=dropdown-menu>
                            <li>@Html.ActionLink("Loại dự án", "Index", "TypeProject")</li>
                            <li>@Html.ActionLink("Kết thúc dự án", "Index", "EndProject")</li>
                            <li>@Html.ActionLink("Đánh giá chất lượng", "Index", "Quality")</li>
                            <li>@Html.ActionLink("Loại ứng dụng", "Index", "TypeApp")</li>
                        </ul>

                    </li>

                    <li class="dropdown">
                        @Html.ActionLink("Nhóm", "Index", "Team")
                        
                    </li>

                    <li class="dropdown">
                        @Html.ActionLink("Nhân sự", "Index", "Staff")
                        <ul class=dropdown-menu>
                            <li>@Html.ActionLink("Nhân lực", "Index", "Resource")</li>
                            <li>@Html.ActionLink("Năng lực", "Index", "Skills")</li>
                            <li>@Html.ActionLink("Chức vụ", "Index", "Positions")</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("Khách hàng", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Báo cáo", "Index", "Chart")</li>
                    
                    <li class="dropdown">
                        @Html.ActionLink("Hóa đơn", "Index", "Invoice")
                        <ul class=dropdown-menu>
                            <li>@Html.ActionLink("Hóa đơn chi tiết", "ExportInvoiceDetails", "Project")</li>
                        </ul>
                    </li>
                </ul>

                @* Đăng nhập + Đăng xuất *@
                <ul style="float:right" class="nav navbar-nav">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Đăng nhập", "Login", "Account")</li>
                    }
                    else
                    {
                        @*<li><a href="#">Hi! @User.Identity.Name</a></li>*@
                        <li>@Html.ActionLink("Hi! " + User.Identity.Name, "ChangePassword", "Account")</li>
                        <li>@Html.ActionLink("Đăng xuất", "Logout", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Thông tin chất lượng dự án</p>
        </footer>
    </div>
</body>
</html>