Source/Controllers/StaffController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System;
using QLCLDA.Models.Entity;

namespace QLCLDA.Controllers
{
    public class StaffController : Controller
    {
        private readonly qlcldaEntities _db = new qlcldaEntities();

        // GET: /Staff/
        public ActionResult Index()
        {
            return View(_db.staffs.Where(s => s.is_deleted == false).ToList());
        }

        // GET: /Staff/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var staff = _db.staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }

            return View(staff);
        }

        // GET: /Staff/Create
        public ActionResult Create()
        {
            ViewBag.team_id = new SelectList(_db.teams, "id", "name");
            ViewBag.position_id = new SelectList(_db.positions, "id", "name");
             var t = _db.type_skill.Include(x => x.skills).ToList();
            ViewBag.type_skill = t;
            return View();
        }

        // POST: /Staff/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,email,skype,phone,position_id,display_order")] staff staff, int? team_id)
        {

            if (team_id.HasValue)
            {
                staff.team_staff.Add(new team_staff { id_team = team_id.Value, is_main_team = true });
            }
            if (ModelState.IsValid)
            {
                _db.staffs.Add(staff);
                _db.SaveChanges();

                return RedirectToAction("AddSkill/"+ staff.id);
            }
            
            return View(staff);
        }

        // GET: /Staff/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var mainTeam = from ts in _db.team_staff
                              where ts.id_staff == id.Value && ts.is_main_team == true
                              select ts.id_team;
            var mt = mainTeam.ToList();
            ViewBag.team_id = mt.Count > 0 ? new SelectList(_db.teams, "id", "name", mt.First()) : new SelectList(_db.teams, "id", "name");
            staff s = _db.staffs.Find(id);

            ViewBag.position_id = new SelectList(_db.positions, "id", "name", s.position_id);
            var staff = _db.staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: /Staff/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,email,skype,phone,position_id,display_order")] staff staff, int? team_id)
        {
            var ts = _db.team_staff.Where(s => s.id_staff == staff.id && s.is_main_team == true).ToList();
            var mainTeam = ts.First();
            if (ts.Count > 0)
            {
                if (team_id.HasValue)
                {
                    mainTeam.id_team = team_id.Value;

                }
                else
                {
                    mainTeam.is_main_team = false;
                }
            }
            else
            {
                if (team_id.HasValue)
                    staff.team_staff.Add(new team_staff { id_team = team_id.Value, is_main_team = true });
            }

            if (ModelState.IsValid)
            {
                _db.Entry(staff).State = EntityState.Modified;
                //db.Entry(_staff).CurrentValues.SetValues(staff);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: /Staff/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var staff = _db.staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: /Staff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            staff staff = _db.staffs.Find(id);
            //foreach (var item in _db.team_staff)
            //{
            //    if (item.id_staff == id)
            //    {
            //        _db.team_staff.Remove(item);
            //    }
            //}

            //foreach (var r in staff.resources)
            //{
            //    foreach (var w in r.works)
            //    {
            //        _db.works.Remove(w);
            //    }
            //    _db.resources.Remove(r);
            //}
            //foreach (var s in _db.staff_of_skill)
            //{
            //    if (s.staff_id == id)
            //    {
            //        _db.staff_of_skill.Remove(s);
            //    }
            //}
            try
            {
                //_db.staffs.Remove(staff);
                staff.is_deleted = true;
                _db.Entry(staff).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Không xóa được vì nhân sự này đang trong dự án");
            }
            return View(staff);
        }


        public ActionResult AddSkill(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var staffOfSkill = _db.staff_of_skill.Where(s => s.staff_id == id).ToList();

            ViewBag.ParentSkills = _db.skills.Where(s => s.parent_skill_id == null).ToList();
            ViewBag.ChildSkills = _db.skills.Where(s => s.parent_skill_id != null).ToList();
            ViewBag.SkillLevels = _db.levels.ToList();

            return View(staffOfSkill);
        }

        [HttpPost]
        public ActionResult AddSkill(int id, string[] skills, string[] levels, string[] num_exp)
        {
            var oldData = _db.staff_of_skill.Where(s => s.staff_id == id);
            if (oldData.Any())
            {
                _db.staff_of_skill.RemoveRange(oldData);
                _db.SaveChanges();
            }

            for (int i = 0; i < skills.Count(); i++)
            {
                var staffSkill = new staff_of_skill
                {
                    staff_id = id,
                    skill_id = Convert.ToInt32(skills[i]),
                    level_id = Convert.ToInt32(levels[i]),
                    num_exp = Convert.ToInt32(num_exp[i])
                };

                _db.staff_of_skill.Add(staffSkill);
            }

            _db.SaveChanges();

            return View("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Source/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QLCLDA.Models;
using QLCLDA.Models.Entity;

namespace QLCLDA.Controllers
{
    public class TeamController : Controller
    {
        private readonly qlcldaEntities _db = new qlcldaEntities();

        // GET: /Team/
        public ActionResult Index()
        {
            var q = _db.teams.OrderBy(x => x.display_order).Include(s => s.team_staff).ToList();
            foreach (var team in q)
            {
                GetStaffInTeam(team);
            }

            return View(_db.teams.OrderBy(x => x.display_order).ToList());
        }

        // GET: /Team/Details/5
        public ActionResult Details(int? id, string startdate, string enddate)
        {
            startdate = string.IsNullOrEmpty(startdate) ? "01/01/2000" : startdate;
            enddate = string.IsNullOrEmpty(enddate) ? "01/01/2222" : enddate;
            IFormatProvider culture = new System.Globalization.CultureInfo("fr-FR", true);
            var sd = DateTime.Parse(startdate, culture, System.Globalization.DateTimeStyles.AssumeLocal);
            var ed = DateTime.Parse(enddate, culture, System.Globalization.DateTimeStyles.AssumeLocal);
            var d = from w in _db.works
                    where w.work_day >= sd && w.work_day <= ed
                    group w by w.work_day into g
                    select g.Key;
            ViewBag.day = d.OrderBy(x => x.Value).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var team = _db.teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
           /* var day = from ts in team.team_staff
                      from r in ts.staff.resources
                      from w in r.works
                      group w by w.work_day into g
                      select g.Key;
            ViewBag.day = day.OrderBy(x => x.Value).ToList();*/



            return View(team);
        }

        // GET: /Team/Create
        public ActionResult Create()
        {
            var team = new team { team_staff = new List<team_staff>() };
            PopulateAssignedStaffData(team);
            return View();
        }

        // POST: /Team/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,workplace,technique,display_order")] team team, string[] to_select_list, string[] leader_select_list)
        {
            if (to_select_list != null || leader_select_list != null)
            {
                team.team_staff = new List<team_staff>();

                if (to_select_list != null)
                {
                    foreach (var staff in to_select_list)
                    {
                        var staffToAdd = new team_staff { id_staff = int.Parse(staff), leader = false, is_main_team = true };
                        team.team_staff.Add(staffToAdd);
                    }
                }

                if (leader_select_list != null)
                {
                    foreach (var staff in leader_select_list)
                    {
                        var leaderToAdd = new team_staff { id_staff = int.Parse(staff), leader = true, is_main_team = true };
                        team.team_staff.Add(leaderToAdd);
                    }
                }
            }

            if (ModelState.IsValid)
            {
                _db.teams.Add(team);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(team);
        }

        // GET: /Team/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //team team = db.teams.Find(id);

            team team = _db.teams.Include(i => i.team_staff).Single(i => i.id == id);
            PopulateAssignedStaffData(team);

            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: /Team/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] to_select_list, string[] leader_select_list)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var teamToUpdate = _db.teams.Include(i => i.team_staff).Single(i => i.id == id);

            if (TryUpdateModel(teamToUpdate, ""))
            {
                try
                {
                    UpdateTeamStaffs(to_select_list, leader_select_list, teamToUpdate);

                    _db.Entry(teamToUpdate).State = EntityState.Modified;
                    _db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateAssignedStaffData(teamToUpdate);
            return View(teamToUpdate);
        }

        // GET: /Team/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            team team = _db.teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: /Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            team team = _db.teams.Find(id);

            var q = _db.team_staff;
            foreach (var staff in q.Where(staff => staff.id_team == team.id))
            {
                _db.team_staff.Remove(staff);
            }

            var allProjects = new HashSet<int>(team.projects.Select(p => p.id));
            foreach (var project in _db.projects)
            {
                if (allProjects.Contains(project.id))
                {
                    team.projects.Remove(project);
                }
            }

            _db.teams.Remove(team);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Lấy danh sách nhân sự đã có trong team
        private void GetStaffInTeam(team team)
        {
            var allStaffs = _db.staffs;
            var teamStaffs = new HashSet<int>(team.team_staff.Where(c => c.leader == false).Select(c => c.id_staff));
            var teamLeaders = new HashSet<int>(team.team_staff.Where(c => c.leader == true).Select(c => c.id_staff));

            var viewModel = new List<AssignedStaffData>();
            var viewLeader = new List<AssignedLeaderData>();

            foreach (var staff in allStaffs)
            {
                if (teamStaffs.Contains(staff.id))
                {
                    viewModel.Add(new AssignedStaffData
                    {
                        StaffId = staff.id,
                        Name = staff.name
                    });
                }

                if (teamLeaders.Contains(staff.id))
                {
                    viewLeader.Add(new AssignedLeaderData
                    {
                        LeaderId = staff.id,
                        Name = staff.name
                    });
                }
            }
            team.getStaffs = viewModel;
            team.getLeaders = viewLeader;
        }

        // Lấy danh sách nhân sự (Thông qua View Model A.S.D)
        private void PopulateAssignedStaffData(team team)
        {
            var allStaffs = _db.staffs;

            var staffsInTeam = new HashSet<int>(team.team_staff.Select(c => c.id_staff));
            var teamStaffs = new HashSet<int>(team.team_staff.Where(c => c.leader != true).Select(c => c.id_staff));
            var leaderTeams = new HashSet<int>(team.team_staff.Where(l => l.leader == true).Select(l => l.id_staff));

            var viewModel = new List<AssignedStaffData>();
            var viewLeader = new List<AssignedLeaderData>();
            var viewSit = new List<AssignedSit>();

            foreach (var staff in allStaffs)
            {
                viewSit.Add(new AssignedSit
                {
                    StaffId = staff.id,
                    Name = staff.name,
                    Assigned = staffsInTeam.Contains(staff.id)
                });

                viewModel.Add(new AssignedStaffData
                {
                    StaffId = staff.id,
                    Name = staff.name,
                    Assigned = teamStaffs.Contains(staff.id)
                });

                viewLeader.Add(new AssignedLeaderData
                {
                    LeaderId = staff.id,
                    Name = staff.name,
                    Assigned = leaderTeams.Contains(staff.id)
                });
            }

            ViewBag.Staffs = viewModel;
            ViewBag.Leaders = viewLeader;
            ViewBag.SIT = _db.staffs.Where(s => s.team_staff.Any() != true).ToList();
        }

        // Update dữ liệu trong bảng team_staff
        private void UpdateTeamStaffs(IEnumerable<string> selectedStaffs, string[] selectedLeader, team teamToUpdate)
        {

Source/Views/Team/Create.cshtml
@model QLCLDA.Models.Entity.team
@using QLCLDA.Helpers

@{
    ViewBag.Title = "Thêm mới nhóm";
}

<script language="javascript" type="text/javascript">

    //this will move selected items from source list to destination list
    function move_list_items(sourceid, destinationid) {
        $("#" + sourceid + "  option:selected").appendTo("#" + destinationid);
    }

    //this will move all selected items from source list to destination list
    function move_list_items_all(sourceid, destinationid) {
        $("#" + sourceid + " option").appendTo("#" + destinationid);
    }

    function selectAllOptions(selStr, selStr2) {
        var selObj = document.getElementById(selStr);
        for (var i = 0; i < selObj.options.length; i++) {
            selObj.options[i].selected = true;
        }

        var selObj2 = document.getElementById(selStr2);
        for (var i = 0; i < selObj2.options.length; i++) {
            selObj2.options[i].selected = true;
        }
    }
</script>

<h2>Thêm mới nhóm</h2>

@using (Html.BeginForm("Create", "Team", FormMethod.Post, new { onsubmit = "selectAllOptions('to_select_list', 'leader_select_list')" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.name, new { @class = "form-control", required = "required", placeholder = "Cần thiết" })
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.workplace, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.workplace, new { @class = "form-control", required = "required", placeholder = "Cần thiết" })
                @Html.ValidationMessageFor(model => model.workplace)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.technique, new { @class = "control-label col-md-2", required = "required", placeholder = "Cần thiết" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.technique, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.technique)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.display_order, new { @class = "control-label col-md-2", required = "required", placeholder = "Cần thiết" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.display_order, new { @class = "form-control", type = "number", min = 1 })
                @Html.ValidationMessageFor(model => model.display_order)
            </div>
        </div>


        @*Select staff to team*@
        <div class="form-group">
            <label class="control-label col-md-2">Nhân sự</label>
            <div class="col-md-10">
                <table cellpadding="5" cellspacing="5">
                    <tbody>
                        <tr>
                            <td colspan="2">
                                <p>Nhân sự có sẵn</p>
                                <select id="from_select_list" multiple="multiple" name="from_select_list" style="height: 150px; width: 200px">
                                    @{
    List<QLCLDA.Models.Entity.staff> staffsInTeam = ViewBag.SIT;
    foreach (var staff in staffsInTeam)
    {
        <option value="@staff.id">@staff.name</option>
    }
                                    }
                                </select>
                            </td>

                            <td colspan="2">
                                <p>Nhân sự trong nhóm</p>
                                <select id="to_select_list" multiple="multiple" name="to_select_list" style="height: 150px; width: 200px"></select>
                            </td>

                            <td colspan="2">
                                <p>Trưởng nhóm</p>
                                <select id="leader_select_list" multiple="multiple" name="leader_select_list" style="height: 150px; width: 200px"></select>
                            </td>
                        </tr>

                        <tr>
                            <td><input id="moveright" type="button" value="Vào nhóm" onclick="move_list_items('from_select_list','to_select_list');" /></td>
                            <td><input id="moverightall" type="button" value="Vào tất cả" onclick="move_list_items_all('from_select_list','to_select_list');" /></td>
                            <td><input id="moveleft" type="button" value="Ra nhóm" onclick="move_list_items('to_select_list','from_select_list');" /></td>
                            <td><input id="moveleftall" type="button" value="Ra tất cả" onclick="move_list_items_all('to_select_list','from_select_list');" /></td>

                            <td><input id="moveright" type="button" value="Trưởng nhóm" onclick="move_list_items('to_select_list', 'leader_select_list');" /></td>
                            <td><input id="moveleft" type="button" value="Bỏ" onclick="move_list_items('leader_select_list', 'to_select_list');" /></td>
                        </tr>
                    </tbody>
                </table>
                <p>* Giữ <strong>Shift</strong> hoặc <strong>Ctrl</strong> để lựa chọn nhiều người</p>
            </div>
        </div>
        @*End - Select Staff to Team*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Html.Button("Quay lại", "Index")

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Source/Views/Team/Details.cshtml
@model QLCLDA.Models.Entity.team
@using System.Diagnostics
@using QLCLDA.Helpers

@{
    ViewBag.Title = "Chi tiết nhóm " + @Model.name;
}

<h2>Chi tiết nhóm @Model.name</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.display_order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.display_order)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.workplace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.workplace)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.technique)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.technique)
        </dd>

    </dl>
</div>
<div style="margin-left:50px;margin-right:50px">
    <label>Danh sách nhân viên</label>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    Tên
                </th>
                <th>
                    Chức vụ
                </th>
                <th>
                    Email
                </th>
                <th>
                    Skype
                </th>
                <th>
                    Điện thoại
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ts in Model.team_staff.OrderBy(x => x.staff.display_order))
            {
                <tr>
                    <td>
                        @Html.ActionLink(HttpUtility.HtmlDecode(Html.DisplayFor(modelItem => ts.staff.name).ToString()), "Details/" + ts.staff.id, "Staff", null, new { id = ts.staff.id })
                    <td>
                        @Html.DisplayFor(modelItem => ts.staff.position.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => ts.staff.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => ts.staff.skype)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => ts.staff.phone)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@{
    var days = ViewBag.day as List<DateTime?>;
}


<div style="margin-left:50px" id="choose_date">
    <label>Khối lượng công việc của nhóm theo ngày</label>
    <form method="get">
        <fieldset>
            <div id="dateDepartHolder">
                <div id="dateDepartHolder">
                    <input type="hidden" name="choose" value="date" />
                    <label for="dateDepart">Ngày bắt đầu</label>
                    <input type="text" id="dateDepart" name="startdate" value="@ViewBag.startdate" onkeydown="return false" data-placeholder="depart" placeholder="start date" autocomplete="off" tabindex="3" />

                    <label for="dateReturn">Ngày kết thúc</label>
                    <input type="text" id="dateReturn" name="enddate" value="@ViewBag.enddate" onkeydown="return false" data-placeholder="return" placeholder="end date" autocomplete="off" tabindex="4" />
                    <button id="save" class="btn btn-primary">Lọc</button>
                </div>
            </div>
            
        </fieldset>
    </form>
</div>
<br/>
<div style="margin-left: 50px; margin-right: 50px; overflow-x: scroll">
    
    <table class="table table-bordered">
        <tbody>
            <tr>
                @{
                    Debug.Assert(days != null, "days != null");
                }
                @foreach (var day in days)
                {

                    var sumStaff = 0;
                    foreach (var r in Model.team_staff.SelectMany(ts => ts.staff.resources))
                    {
                        var day1 = day;
                        foreach (var w in r.works.Where(w => w.work_day != null && DateTime.Compare(day1.Value, w.work_day.Value) == 0))
                        {
                            if (w.percent != null)
                            {
                                sumStaff += w.percent.Value;
                            }
                            break;
                        }
                    }
                    var str = sumStaff + "%";
                    if (sumStaff < Model.team_staff.Count * 100)
                    {
                        <td style="background-color:#FFCCCC;color:#ff0000">
                            @str
                        </td>
                    }
                    else if (sumStaff > Model.team_staff.Count * 100)
                    {
                        <td style="background-color:#ccffcc;color:#00cc00">
                            @str
                        </td>
                    }
                    else
                    {
                        <td>
                            @str
                        </td>
                    }

                }
            </tr>
        </tbody>

        <thead>
            <tr>
                @{
                    Debug.Assert(days != null, "days != null");
                }
                @foreach (var day in days)
                {
                    <th>
                        @day.Value.ToString("dd/MM/yyy")
                    </th>
                }
            </tr>
        </thead>
    </table>
</div>
<div style="margin-left: 50px; margin-right: 50px">Max: @Model.team_staff.Count*100 %</div>
    <p>
        @Html.Button("Sửa", "Edit", new { id = Model.id })

        @Html.Button("Quay lại", "Index")
    </p>

Source/Views/Team/Index.cshtml
@model IEnumerable<QLCLDA.Models.Entity.team>
@using QLCLDA.Helpers

@{
    ViewBag.Title = "Danh sách nhóm";
}

<h2>Danh sách nhóm</h2>

<p>
    @Html.Button("Thêm mới","Create")
</p>

<table id="example" class="table table-bordered">
    <thead>
        <tr>
            <th>
                STT
            </th>
            <th>
                Tên
            </th>
            <th>
                Nơi làm việc
            </th>
            <th>
                Kỹ thuật
            </th>
            <th>
                Trưởng nhóm
            </th>
            <th></th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th>
                STT
            </th>
            <th>
                Tên
            </th>
            <th>
                Nơi làm việc
            </th>
            <th>
                Kỹ thuật
            </th>
            <th>
                Trưởng nhóm
            </th>
            <th></th>
        </tr>
    </tfoot>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.display_order)
                </td>
                <td>
                    @Html.ActionLink(HttpUtility.HtmlDecode(Html.DisplayFor(modelItem => item.name).ToString()), "Details", new { id = item.id })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.workplace)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.technique)
                </td>
                <td>
                    @foreach (var leader in item.getLeaders)
                    {
                        @Html.ActionLink(leader.Name, "Details", "Staff", new { id = leader.LeaderId }, "") <br />
                    }
                </td>
                <td>
                    @Html.Button("Sửa", "Edit", new { id = item.id })
                    @Html.Button("Xóa", "Delete", new { id = item.id })
                </td>
            </tr>
        }
    </tbody>
</table>

<p>
    @Html.Button("Thêm mới", "Create")
</p>