Source/Controllers/ActivityController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QLCLDA.Models;
using QLCLDA.Models.Entity;

namespace QLCLDA.Controllers
{
    public class ActivityController : Controller
    {
        private readonly qlcldaEntities _db = new qlcldaEntities();

        // GET: /Activity/
        public ActionResult Index()
        {
            var activityLog = _db.activity_log.Include(a => a.project);
            return View(activityLog.ToList());
        }

        // GET: /Activity/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            activity_log activityLog = _db.activity_log.Find(id);
            if (activityLog == null)
            {
                return HttpNotFound();
            }
            return View(activityLog);
        }

        // GET: /Activity/Create
        public ActionResult Create()
        {
            ViewBag.id_project = new SelectList(_db.projects, "id", "name_project");
            return View();
        }

        // POST: /Activity/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,id_project,who_activity,date_update,content_update")] activity_log activityLog)
        {
            if (ModelState.IsValid)
            {
                _db.activity_log.Add(activityLog);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_project = new SelectList(_db.projects, "id", "name_project", activityLog.id_project);
            return View(activityLog);
        }

        // GET: /Activity/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            activity_log activityLog = _db.activity_log.Find(id);
            if (activityLog == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_project = new SelectList(_db.projects, "id", "name_project", activityLog.id_project);
            return View(activityLog);
        }

        // POST: /Activity/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,id_project,who_activity,date_update,content_update")] activity_log activityLog)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(activityLog).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_project = new SelectList(_db.projects, "id", "name_project", activityLog.id_project);
            return View(activityLog);
        }

        // GET: /Activity/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            activity_log activityLog = _db.activity_log.Find(id);
            if (activityLog == null)
            {
                return HttpNotFound();
            }
            return View(activityLog);
        }

        // POST: /Activity/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            activity_log activityLog = _db.activity_log.Find(id);
            _db.activity_log.Remove(activityLog);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Source/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QLCLDA.ActionSelector;
using Excel = Microsoft.Office.Interop.Excel;
using OfficeOpenXml;
using QLCLDA.Models;
using QLCLDA.Models.Entity;

namespace QLCLDA.Controllers
{
    public class ProjectController : Controller
    {
        private readonly qlcldaEntities _db = new qlcldaEntities();

        // GET: /Project/
        public ActionResult Index()
        {
            var projects = _db.projects.Include(p => p.customer).Include(p => p.end_project).Include(p => p.staff).Include(p => p.quality).Include(p => p.type_project).Include(p => p.type_app);
            return View(projects.ToList());
        }

        // Delete Selected
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string[] foo, int? page)
        {
            var projects = from p in _db.projects
                           select p;

            foreach (var id in foo)
            {
                if (!id.Equals("false"))
                {
                    var project = _db.projects.Find(int.Parse(id));
                    var allTeams = new HashSet<int>(project.teams.Select(t => t.id));
                    foreach (var team in _db.teams.Where(team => allTeams.Contains(team.id)))
                    {
                        project.teams.Remove(team);
                    }
                    _db.projects.Remove(project);
                }
            }
            _db.SaveChanges();

            return View(projects.ToList());
        }

        // Export to Excel
        public ActionResult ToExcelResult(int? id, bank_info bankInfo, string no, string date, string tax, string note)
        {
            if (id != null)
            {
                var newFile = ConvertToExcel(id, bankInfo, no, date, tax, note);

                // Open Dialog Save File
                Response.AddHeader("Content-disposition", "attachment; filename=output.xlsx");
                Response.ContentType = "application/octet-stream";
                Response.TransmitFile(newFile);
                Response.Flush();
                System.IO.File.Delete(newFile);
                Response.End();

                return RedirectToAction("Index");
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // Export to PDF
        public ActionResult ToPdfResult(int? id, bank_info bankInfo, string no, string date, string tax, string note)
        {
            if (id != null)
            {
                var appData = Server.MapPath("~/App_Data");
                var newPdf = string.Format("{0}.pdf", Guid.NewGuid());
                var pdfFile = Path.Combine(appData, newPdf);

                var newFile = ConvertToExcel(id, bankInfo, no, date, tax, note);

                Excel._Application excelApplication = new Excel.Application();

                var paramSourceBookPath = newFile;
                var paramMissing = Type.Missing;

                var paramExportFilePath = pdfFile;
                const Excel.XlFixedFormatType paramExportFormat = Excel.XlFixedFormatType.xlTypePDF;
                const Excel.XlFixedFormatQuality paramExportQuality = Excel.XlFixedFormatQuality.xlQualityStandard;
                const bool paramOpenAfterPublish = false;
                const bool paramIncludeDocProps = true;
                const bool paramIgnorePrintAreas = true;
                var paramFromPage = Type.Missing;
                var paramToPage = Type.Missing;

                // Open the source workbook.
                var excelWorkBook = excelApplication.Workbooks.Open(paramSourceBookPath,
                    paramMissing, paramMissing, paramMissing, paramMissing,
                    paramMissing, paramMissing, paramMissing, paramMissing,
                    paramMissing, paramMissing, paramMissing, paramMissing,
                    paramMissing, paramMissing);

                // Save it in the target format.
                if (excelWorkBook != null)
                    excelWorkBook.ExportAsFixedFormat(paramExportFormat,
                        paramExportFilePath, paramExportQuality,
                        paramIncludeDocProps, paramIgnorePrintAreas, paramFromPage,
                        paramToPage, paramOpenAfterPublish,
                        paramMissing);

                // Close the workbook object.
                if (excelWorkBook != null)
                {
                    excelWorkBook.Close(false, paramMissing, paramMissing);
                }

                // Quit Excel and release the ApplicationClass object.
                excelApplication.Quit();

                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();

                // Open Dialog Save File
                Response.AddHeader("Content-disposition", "attachment; filename=output.pdf");
                Response.ContentType = "application/octet-stream";
                Response.TransmitFile(paramExportFilePath);
                Response.Flush();
                System.IO.File.Delete(paramSourceBookPath);
                System.IO.File.Delete(paramExportFilePath);
                Response.End();

                return RedirectToAction("Index");
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: /Project/Details/5
        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                var project = _db.projects.Find(id);
                ViewBag.BrSE_Name = _db.staffs.Single(s => s.id == project.brse).name;

                if (project == null)
                {
                    return HttpNotFound();
                }
                return View(project);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: /Project/Create
        public ActionResult Create()
        {
            var project = new project { teams = new List<team>() };
            PopulateAssignedTeamData(project);

            var proLanguage = _db.skills.Where(x => x.type_skill.id == 1).ToList();
            ViewBag.apps = _db.type_app.ToList();
            ViewBag.proLang = proLanguage;
            ViewBag.id_customer = new SelectList(_db.customers, "id", "company");
            //ViewBag.id = new SelectList(_db.end_project, "project_id", "difficulty");
            ViewBag.pm = new SelectList(_db.staffs.Where(x => x.position.id == 1), "id", "name");
            //ViewBag.id = new SelectList(_db.qualities, "project_id", "project_id");
            ViewBag.brse = new SelectList(_db.staffs.Where(x => x.position.id == 2), "id", "name");
            ViewBag.id_type_project = new SelectList(_db.type_project, "id", "name");
            return View();
        }

        // POST: /Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,id_customer,id_type_project,name_cd,name_project,expected_start_date,expected_end_date,actual_start_date,actual_end_date,technology,purpose,estimator,scale_estimator,contract_value,pm,brse,current_cost,estimated_cost,software,hardware")] project project, string[] selectedProLang, string[] selectedApps, string[] selectedTeams)
        {
            var userId = User.Identity.Name;
            if (selectedTeams != null)
            {
                project.teams = new List<team>();
                foreach (var team in selectedTeams)
                {
                    var teamToAdd = _db.teams.Find(int.Parse(team));
                    project.teams.Add(teamToAdd);
                }
            }
            if (selectedProLang != null)
            {
                project.skills = new List<skill>();
                foreach (var pl in selectedProLang)
                {
                    var pro = _db.skills.Find(int.Parse(pl));
                    project.skills.Add(pro);
                }
            }

            if (selectedApps != null)
            {
                project.type_app = new List<type_app>();
                foreach (var app in selectedApps)
                {
                    var ta = _db.type_app.Find(int.Parse(app));
                    project.type_app.Add(ta);
                }
            }

            if (ModelState.IsValid)
            {
                _db.projects.Add(project);
                _db.SaveChanges(userId, project);
                //var activity = new AuditLog(project, UserID);
                return RedirectToAction("Index");
            }

            ViewBag.id_customer = new SelectList(_db.customers, "id", "company", project.id_customer);
            ViewBag.pm = new SelectList(_db.staffs.Where(x => x.position.name == "PM"), "id", "name");
            ViewBag.brse = new SelectList(_db.staffs.Where(x => x.position.name == "BrSE"), "id", "name");
            ViewBag.id_type_project = new SelectList(_db.type_project, "id", "name", project.id_type_project);

            PopulateAssignedTeamData(project);
            return View(project);
        }

        // GET: /Project/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var project = _db.projects.Include(i => i.teams).Include(i => i.type_app).Include(i => i.skills).Single(i => i.id == id);


            if (project == null)
            {
                return HttpNotFound();

Source/Views/Activity/Create.cshtml
@using QLCLDA.Helpers
@model QLCLDA.Models.Entity.activity_log

@{
    ViewBag.Title = "Thêm kỹ năng";
}

<h2>Thêm kỹ năng</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>activity_log</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.id_project, "id_project", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_project", String.Empty)
                @Html.ValidationMessageFor(model => model.id_project)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.who_activity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.who_activity)
                @Html.ValidationMessageFor(model => model.who_activity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_update, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.date_update)
                @Html.ValidationMessageFor(model => model.date_update)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content_update, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.content_update)
                @Html.ValidationMessageFor(model => model.content_update)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.Button("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Source/Views/Activity/Delete.cshtml
@model QLCLDA.Models.Entity.activity_log

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>activity_log</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.who_activity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.who_activity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_update)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_update)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.content_update)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.content_update)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.project.name_cd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.project.name_cd)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Source/Views/Activity/Details.cshtml
@model QLCLDA.Models.Entity.activity_log

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>activity_log</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.who_activity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.who_activity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_update)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_update)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.content_update)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.content_update)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.project.name_cd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.project.name_cd)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Source/Views/Activity/Edit.cshtml
@model QLCLDA.Models.Entity.activity_log

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>activity_log</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.id_project, "id_project", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_project", String.Empty)
                @Html.ValidationMessageFor(model => model.id_project)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.who_activity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.who_activity)
                @Html.ValidationMessageFor(model => model.who_activity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_update, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.date_update)
                @Html.ValidationMessageFor(model => model.date_update)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content_update, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.content_update)
                @Html.ValidationMessageFor(model => model.content_update)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Source/Views/Activity/Index.cshtml
@model IEnumerable<QLCLDA.Models.Entity.activity_log>

@{
    ViewBag.Title = "Nhật ký";
}

<h2>Nhật ký dự án</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

<table id="example" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                Mã
            </th>
            <th>
                User
            </th>
            <th>
                Dự án
            </th>
            <th>
                Thời gian
            </th>
            <th>
                Nội dung
            </th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th>
                Mã
            </th>
            <th>
                User
            </th>
            <th>
                Dự án
            </th>
            <th>
                Thời gian
            </th>
            <th>
                Nội dung
            </th>
        </tr>
    </tfoot>

    <tbody>
        @foreach (var item in Model.Reverse())
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.who_activity)
                </td>
                <td>
                    @Html.ActionLink(HttpUtility.HtmlDecode(Html.DisplayFor(modelItem => item.project.name_project).ToString()), "Details", "Project", new { id = item.id_project }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date_update)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.content_update)
                </td>
            </tr>
        }
    </tbody>
</table>